import type { MiddlewareHandler } from 'hono';
import type { Env } from '../types/env';

/** Security headers for responses generated by the Worker. SPA documents
 * pass through the Worker to opt out of Cloudflare HTML injection; static
 * files bypass it and receive the matching policy from public/_headers.
 * style-src keeps unsafe-inline deliberately: ArtPlayer injects styles and
 * index.html contains the small FOUC guard. */
export const securityHeaders: MiddlewareHandler<{ Bindings: Env }> = async (c, next) => {
  await next();

  c.header(
    'Content-Security-Policy',
    [
      "default-src 'self'",
      "script-src 'self' https://challenges.cloudflare.com",
      "style-src 'self' 'unsafe-inline'",
      "font-src 'self'",
      "img-src 'self' https://image.tmdb.org https://phimimg.com data:",
      "media-src 'self' blob: https:",
      "connect-src 'self' https:",
      'worker-src blob:',
      'frame-src https://player.phimapi.com https://www.youtube.com https://challenges.cloudflare.com',
      "object-src 'none'",
      "base-uri 'none'",
      "frame-ancestors 'self'",
    ].join('; ')
  );
  c.header('Strict-Transport-Security', 'max-age=63072000; includeSubDomains; preload');
  c.header('X-Content-Type-Options', 'nosniff');
  c.header('Referrer-Policy', 'strict-origin-when-cross-origin');
  c.header('Permissions-Policy', 'geolocation=(), microphone=(), camera=()');
};
